function [predicted_EKF_mean_m,predicted_EKF_covar_P] = EKFPrediction( ...
        system_equations, ...
        EKF_mean_m, ...
        EKF_covar_P, ...
        process_noise_variance_Q)
    
    predicted_EKF_mean_m = system_equations.plant_noiseless(EKF_mean_m);
    linear_plant_eval = system_equations.linear_system_matr(EKF_mean_m);
    predicted_EKF_covar_P = linear_plant_eval*EKF_covar_P*linear_plant_eval' ...
        +  process_noise_variance_Q; 
    % TODO: make sure that the linearized system matrix is evaluated at the
    % EKF_mean_m point.
end