function [EKF_mean_m,EKF_covar_P,kalman_gain_K] = EKFUpdate( ...
        system_equations, ...
        predicted_EKF_mean_m, ... 
        predicted_EKF_covar_P, ...
        measurement_noise_variance_R, ...
        measurement_z)
    
    linear_measur_eval = system_equations.linear_sensor_matr(predicted_EKF_mean_m);
    kalman_gain_K = predicted_EKF_covar_P * linear_measur_eval' ...
        /(linear_measur_eval*predicted_EKF_covar_P*linear_measur_eval' ...
        + measurement_noise_variance_R);
    EKF_mean_m = predicted_EKF_mean_m + kalman_gain_K ...
        * (measurement_z - system_equations.sensor_noiseless(predicted_EKF_mean_m));
    EKF_covar_P = ...
        (eye(size(predicted_EKF_covar_P)) - kalman_gain_K*linear_measur_eval) ...
        * predicted_EKF_covar_P;
    EKF_covar_P = 1/2*(EKF_covar_P+EKF_covar_P');
    % z is only a scalar. When the measurement error is weighted according
    % to the Kalman gain, the measurement also modifies the non measured
    % state element. Problematic?
end
