function [state_array,measur_array] = simulateAndMeasure( ...
        simu_time, ...
        dt, ...
        x_init, ...
        determ_fcn, ...
        stoch_fcn, ...
        measure_fcn, ...
        dt_sample, ...
        R)
    
    [x,tx] = stochastic_pendulum_em(simu_time,dt,x_init,determ_fcn,stoch_fcn);
 
    t_sample = 0:dt_sample:simu_time;
    x1_sample = interp1(tx,x(1,:),t_sample);
    x2_sample = interp1(tx,x(2,:),t_sample);
    state_array = [x1_sample; x2_sample];
    
    measur_array = measure_fcn(state_array) + sqrt(R)*randn(size(x1_sample));

end